obj-$(CONFIG_ARCH_ARM_CORTEX_M0)+=cortex-m0/
obj-$(CONFIG_ARCH_ARM_CORTEX_M3)+=cortex-m3/
obj-$(CONFIG_ARCH_ARM_CORTEX_M4F)+=cortex-m4f/
obj-$(CONFIG_MACH_HAS_NVIC)+=nvic/
obj-$(CONFIG_ARCH_ARM_FAULT_HANDLER)+=error/
obj-$(CONFIG_ARCH_ARM_DEBUG) += debug/
