obj-$(CONFIG_ARCH_RISCV_MMODE) += mmode/
obj-$(CONFIG_ARCH_RISCV_SMODE) += smode/
obj-$(CONFIG_ARCH_RISCV_PLIC) += plic/
obj-$(CONFIG_ARCH_RISCV_INIT) += init.o
obj-$(CONFIG_ARCH_SBI) += sbi/

subdir-asflags-y += -include arch/riscv/include/FreeROTSArchConfig.h
